name: Build Android
on:
  workflow_call:
  workflow_dispatch: 

jobs:
  build_matrix:
    strategy:
      matrix:
        arch: ["arm64_v8a", "x86", "x86_64", "armv7"]
        include:
          - arch: arm64_v8a
            ssl_path: arm64-v8a
          - arch: x86
            ssl_path: x86
          - arch: x86_64
            ssl_path: x86_64
          - arch: armv7
            ssl_path: armeabi-v7a
    env:
      BUILD_ARCH: ${{ matrix.arch }}
    runs-on: ubuntu-latest
    container:
      image: stateoftheartio/qt6:6.6-android-aqt
      options: --user root
    timeout-minutes: 60
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get dependencies
      run: ./get_dependencies.sh
    - name: Build qtopcua
      run: |
        HOME_DIR=$(pwd) && \
        mkdir -p build && \
        qt-cmake ./dependencies/qtopcua -G Ninja -B ./build/qtopcua -DCMAKE_INSTALL_PREFIX=/opt/Qt/6.6.1/android_${{ matrix.arch }} -DFEATURE_open62541_security:BOOL=ON -DFEATURE_gds:BOOL=ON -DOPENSSL_INCLUDE_DIR=${HOME_DIR}/dependencies/android_openssl/ssl_3/include/ -DOPENSSL_ROOT_DIR=${HOME_DIR}/dependencies/android_openssl/ssl_3/${{ matrix.ssl_path }}/ && \
        cmake --build ./build/qtopcua && \
        sudo /opt/Qt/Tools/CMake/bin/cmake --install ./build/qtopcua
    - name: Build App
      run: |
        mkdir -p ./build/opc_ua_browser && \
        qt-cmake . -G Ninja -B ./build/opc_ua_browser && \
        cmake --build ./build/opc_ua_browser
